"""add event type

Revision ID: 2c925cd4bbb2
Revises: 73fd0990aac7
Create Date: 2019-12-19 11:59:12.069442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c925cd4bbb2'
down_revision = '73fd0990aac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_type', sa.Enum('event', '_class', 'reservation', name='eventtype'), nullable=False, default='_class'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('event_type')

    # ### end Alembic commands ###
