"""empty message

Revision ID: 3e7bd7794e20
Revises: 
Create Date: 2019-08-23 09:22:05.819186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e7bd7794e20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('wa_group_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('wa_group_id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('instructor_email', sa.String(length=120), nullable=True),
    sa.Column('instructor_name', sa.String(length=60), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('image_file', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('registration_limit', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('sync_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=40), nullable=True),
    sa.Column('availability', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('authorization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['authorization_id'], ['authorization.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], )
    )
    op.create_table('event_platform',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], )
    )
    op.create_table('event_price',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('price_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['price.id'], )
    )
    op.create_table('external_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_event', sa.Boolean(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('ext_event_id', sa.String(length=100), nullable=True),
    sa.Column('ext_event_url', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_event')
    op.drop_table('event_price')
    op.drop_table('event_platform')
    op.drop_table('association')
    op.drop_table('price')
    op.drop_table('platform')
    op.drop_table('event')
    op.drop_table('authorization')
    # ### end Alembic commands ###
