"""Add event status column

Revision ID: 73fd0990aac7
Revises: c212abb5065c
Create Date: 2019-12-19 11:42:23.818957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73fd0990aac7'
down_revision = 'c212abb5065c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'rejected', 'cancelled', 'deleted', name='eventstatus'), nullable=False, default='approved'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
