"""make suplementary tables more consistent

Revision ID: c8b5fda83a1a
Revises: 133e856c92f4
Create Date: 2019-12-19 16:12:47.752203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b5fda83a1a'
down_revision = '133e856c92f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('modified_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.DATETIME(),
               type_=sa.Interval(),
               existing_nullable=False)

    with op.batch_alter_table('event_template', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.DATETIME(),
               type_=sa.Interval(),
               existing_nullable=False)

    with op.batch_alter_table('platform', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('modified_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('modified_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price', schema=None) as batch_op:
        batch_op.drop_column('modified_date')
        batch_op.drop_column('created_date')

    with op.batch_alter_table('platform', schema=None) as batch_op:
        batch_op.drop_column('modified_date')
        batch_op.drop_column('created_date')

    with op.batch_alter_table('event_template', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.Interval(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.Interval(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('authorization', schema=None) as batch_op:
        batch_op.drop_column('modified_date')
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###
